# Generated by Django 6.0.3 on 2026-03-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_exchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
